name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install Scala
      run: sudo apt-get install -y scala
    - name: Install sbt
      run: |
        echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
        curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x99E82A75642AC823" | sudo apt-key add
        sudo apt-get update
        sudo apt-get install -y sbt
    - name: Create test files
      run: |
        mkdir -p src/test/resources
        echo 'included {
  settingA = valueA
  settingB = valueB
}

main {
  setting1 = value1
  setting2 = value2
  include required("src/test/resources/included.conf")
}' > src/test/resources/test.conf
        echo 'included {
  settingA = valueA_from_included
  settingB = valueB_from_included
}' > src/test/resources/included.conf
    - name: Run tests
      run: sbt "testOnly * -- -l src/test/scala"
    - name: Clean up test files
      run: rm -f src/test/resources/test.conf src/test/resources/included.conf
